
version: '2'
    
services:
  rds:
    image: redis:3.2.11
    # ports: 
      # - 6379:6379
    restart: always
  ppp:
    build: ./conf.d
    volumes:
      - ./conf.d:/usr/local/etc/php/conf.d
      - ./:/usr/share/nginx/html
      - ./photos:/data
    depends_on:
      - rds
    restart: always
  ngx:
    image: nginx:1.14.0-alpine
    ports:
      - 27006:80
    volumes:
      - ./conf.d/:/etc/nginx/conf.d
      - ./:/usr/share/nginx/html
      - ./photos:/data
    depends_on:
      - ppp
    restart: always